name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/.buildx-main-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-main-cache
          tags: localhost:5000/vite-phaser/server:latest
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/vite-phaser/server:latest